#!/bin/sh
if [ "$(id -u)" -ne 0 ]; then
  echo "Please run with sudo"
  exit 1
fi
FILENAME="vhusbdarmpi3"
wget https://www.virtualhere.com/sites/default/files/usbserver/$FILENAME --no-check-certificate
chmod +x $FILENAME
mv $FILENAME /usr/local/sbin
mkdir -p /usr/local/etc/virtualhere
if [ -d "/etc/systemd/system" ]; then
  cat << EOF > /etc/systemd/system/virtualhere.service
[Unit]
Description=VirtualHere Server
After=network.target

[Service]
Type=forking
ExecStart=/usr/local/sbin/$FILENAME -b -c /usr/local/etc/virtualhere/config.ini

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
  systemctl enable virtualhere.service
  systemctl start virtualhere.service
else
  echo "Error, only systemd is supported"
fi
